### PR TITLE
Mypy stubs

### PR DESCRIPTION
**Pull request by itdaniher**

### CODE REVIEW

**Comment by cjwelborn** [comment]
Awesome, 2 years but they finally found some use. Do you plan on officially forking this into something else (a new package on PyPi), or was this just for your own use?

Edit: oh I just read the description for bazaar-projects: "Cherry-picking sweet patchsets for abandoned projects since 1970."

**Comment by itdaniher** [comment]
@cjwelborn I very well may publish this on PyPi. I started by hacking on docopt.py to scratch my own itch, discovered a large number of useful patches languishing in upstream. I don't like wasting energy, so I set about merging them in as seemed appropriate. Not planning on stopping! :smile: 

I kind-of-maintain a number of projects @bazaar-projects - they all mostly started out this way - forks of unmaintained stuff to scratch an itch. I've even managed to return ownership for one or two of them back to the original authors!

**Comment by itdaniher** [comment]
@cjwelborn it's done! https://pypi.org/project/docopt-ng/ :)

**Comment by cjwelborn** [comment]
@itdaniher That is awesome. I like what you're doing. Thanks again. 😀

**Pull request merged**
